version: '3.8'

services:
  web:
    build: .
    environment:
      - OPENAI_API_KEY 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
    command: uvicorn supabase_main:app --host 0.0.0.0 --port 9000
    ports:
      - 9000:9000